### ISSUE TITLE
[CHECKLIST]: NEW REPOSITORY SETTINGS

### ISSUE THREAD

**Issue by RChloe** [tektronix/Programmatic-Control-Examples#58]
### Have you added any of the following to your repo yet?

- [ ] -[README that follows guidelines](https://github.com/tektronix/best-practice-resources/blob/main/README-templates)
- [X] -[LICENSE](https://github.com/tektronix/best-practice-resources/blob/main/README.md#license)
- [ ] -[Global Codeowner](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#codeowners)
- [ ] -[Branch Protection](https://github.com/tektronix/best-practice-resources/blob/main/README.md#branch-protection)
- [ ] -[dependabot](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#dependabot)
- [ ] -[Repo Lint Action](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#repo-lint)
- [ ] -[CodeScan](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#codescan)
- [ ] -[About description with topics](https://github.com/tektronix/best-practice-resources/blob/main/README.md#topics)
